include_guard()

function(disable_target_warnings target_name)
    if(NOT TARGET ${target_name})
        message(FATAL_ERROR "Target ${target_name} does not exist")
    endif()

    get_target_property(target_type ${target_name} TYPE)

    if(target_type STREQUAL "INTERFACE_LIBRARY")
        if(MSVC)
            target_compile_options(${target_name} INTERFACE /W0)
            set(_warn_flag "/W0")
        else()
            target_compile_options(${target_name} INTERFACE -w)
            set(_warn_flag "-w")
        endif()
    else()
        if(MSVC)
            target_compile_options(${target_name} PRIVATE /W0)
            set(_warn_flag "/W0")
        else()
            target_compile_options(${target_name} PRIVATE -w)
            set(_warn_flag "-w")
        endif()
    endif()

    message(STATUS "Disabled warnings for target '${target_name}' using flag '${_warn_flag}'")
endfunction()